/*
    FileName:     MyView
    Author:       8ucchiman
    CreatedDate:  2023-09-19 14:56:09
    LastModified: 2023-02-26 13:30:39 +0900
    Reference:    8ucchiman.jp
    Description:  ---
*/

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Async01{
    using Terminal.Gui;
    
    
    public partial class MyView {
        
        public MyView() {
            InitializeComponent();
            count_button.Clicked += () => this.count_button.Text = _count++.ToString();
            thread_button.Clicked += () => {
                var t = new Thread(GetDataAsync);
                t.Start();
            };
        }

        private void GetDataAsync () {        // 非同期は必ず戻り値なし(void)
            var dtos = new List<DTO>();
            for (int i=0; i<5; i++) {
                Thread.Sleep(1000);
                dtos.Add(new DTO(i.ToString(), DateTime.Now.ToString("HH:mm:ss")));
            }


            ///
            /// this.Invokeを使う理由
            /// ワーカースレッド上で画面のコントロールを操作をしてはいけないため
            /// 画面のコントロールの操作はUIスレッドのみ行える
            /// なお, terminal.guiではwindows.formではないためInvokeメソッドは使えない
            ///
            // this.Invoke((Action)delegate () {
            //         MessageBox.Query("Done", "!!!!");
            // });
            // Application.MainLoop.Invoke((Action)delegate () {
            //         MessageBox.Query("Done", "Threaddddddddd");
            //         });
            Application.MainLoop.Invoke(() => {
                    MessageBox.Query("Done", "Threadd");
                    });
        }

        private sealed class DTO {
            public DTO (string id, string datadate) {
                Id = id;
                DataDate = datadate;
            }

            public string Id {get; set;}
            public string DataDate {get; set;}
        }
    }
}
