#
# FileName:     Makefile
# Author: 		8ucchiman
# CreatedDate:  2023-09-25 13:42:27
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 	https://qiita.com/chibi929/items/b8c5f36434d5d3fbfa4a
# Description:	---
#


.PHONY: run clean


run:
	dotnet run

clean:
	dotnet clean


