#
# FileName:     Makefile
# Author: 		8ucchiman
# CreatedDate:  2023-10-04 15:03:58
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 	https://qiita.com/chibi929/items/b8c5f36434d5d3fbfa4a
# Description:	---
#




.PHONY: run clean debug


run:
	dotnet run

debug:


clean:
	dotnet clean


