
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace listview_sample02 {
    using System;
    using Terminal.Gui;
    
    
    public partial class QueueView : Terminal.Gui.Window {
        
        private void InitializeComponent() {
            this.Width = Dim.Percent(20);
            this.Height = Dim.Fill(0) - 10;
            this.X = 10;
            this.Y = 10;
            Console.WriteLine($"{this.X}, {this.Y}, {this.Width}, {this.Height}");
            this.Modal = false;
            this.ColorScheme = Colors.Error;
            this.Text = "QueueView";
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Rounded;
            this.Border.Effect3D = true;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Press Ctrl+Q to quit";

            this.Add(
                new Label(3, 2, "Choose Service: "),
                new ListView(new Rect(20, 2, 16, 4), new string[] {
                    "Opizo",
                    "Bitly",
                }),
                new TextField(20, 6, 40, ""),
                new Button(3, 14, "Ok"),
                new Button(10, 14, "Cancel"));

        }
    }

    public partial class TimeLapseView : Terminal.Gui.Window {
        private void InitializeComponent () {
        }
    }
}
