
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace listview_sample02 {
    using System;
    using Terminal.Gui;
    
    
    public partial class QueueView : Terminal.Gui.Window {
        
        private void InitializeComponent() {
            this.Width = 20;
            this.Height = 20;
            this.X = 10;
            this.Y = 10;
            // this.Modal = false;
            // this.ColorScheme = Colors.Error;
            // this.Text = "QueueView";
            // this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            // this.Border.Effect3D = true;
            // this.Border.DrawMarginFrame = true;
            // this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            // this.Title = "Press Ctrl+Q to quit";

            var listView = new ListView() {
                X = 1,
                Y = 2,
                Height = Dim.Fill(),
                Width = Dim.Fill(1),
                AllowsMarking = false,
                AllowsMultipleSelection = false
            };

            var currentDirectory = Environment.CurrentDirectory;
            var files = Directory.GetFiles(currentDirectory);
            Console.WriteLine($"{files}");
            listView.SetSource(files);

            this.Add(
                listView
            );
        }
    }

    public partial class TimeLapseView : Terminal.Gui.Window {
        private void InitializeComponent () {
        }
    }
}
